name: BEconomia
version: 1.0
main: br.felps.economia.Economia
api-version: 1.20

commands:
  money:
    description: Mostra quantos coins você tem ou define coins de um jogador
    usage: /money ou /money set <jogador> <quantia>
  pay:
    description: Transfere coins para um jogador
    usage: /pay <jogador> <quantia>
  topmoney:
    description: Mostra os top 5 jogadores com mais coins

permissions:
  economia.setmoney:
    description: Permite definir coins de um jogador
    default: op
